SWIG_80 = [
    "1AT",
    "ABS",
    "ACG",
    "AGO",
    "ALL",
    "AMB",
    "AMC",
    "APT",
    "ARH",
    "ARL",
    "AST",
    "ATC",
    "BCX",
    "BIO",
    "BLO",
    "BMC",
    "BOS",
    "BRS",
    "CIG",
    "CLC",
    "CLN",
    "CMP",
    "COG",
    "CRI",
    "CRJ",
    "CTX",
    "DAD",
    "DAT",
    "DCR",
    "ECH",
    "ELT",
    "ENT",
    "ERB",
    "FRO",
    "FTE",
    "GEA",
    "GRX",
    "KGN",
    "LWB",
    "MAB",
    "MCI",
    "MCR",
    "MDG",
    "MLG",
    "MLS",
    "MNC",
    "MRC",
    "MSZ",
    "MUR",
    "OND",
    "OPN",
    "PBX",
    "PCR",
    "PLW",
    "PXM",
    "QRS",
    "RVU",
    "SCP",
    "SEL",
    "SGN",
    "SHO",
    "SKA",
    "SLV",
    "SNK",
    "STP",
    "STX",
    "SVE",
    "TAR",
    "TOA",
    "TOR",
    "UNI",
    "UNT",
    "VGO",
    "VOT",
    "VRG",
    "WLT",
    "WTN",
    "WWL",
    "XTP",
    "ZEP",
]

MWIG_40 = [
    "11B",
    "ABE",
    "ACP",
    "APR",
    "ASB",
    "ASE",
    "ATT",
    "BFT",
    "BHW",
    "BNP",
    "CAR",
    "CBF",
    "CPS",
    "DIA",
    "DOM",
    "DVL",
    "EAT",
    "ENA",
    "EUR",
    "GPP",
    "GPW",
    "HUG",
    "ING",
    "JSW",
    "LBW",
    "MBR",
    "MIL",
    "MRB",
    "NEU",
    "NWG",
    "PEP",
    "RBW",
    "SNT",
    "TEN",
    "TPE",
    "TXT",
    "VOX",
    "VRC",
    "WPL",
    "XTB"
]

WIG_20 = [
    "ALE",
    "ALR",
    "BDX",
    "MDV",
    "CDR",
    "DNP",
    "KGH",
    "KRU",
    "KTY",
    "LPP",
    "MBK",
    "OPL",
    "PCO",
    "PEO",
    "PGE",
    "PKN",
    "PKO",
    "PZU",
    "EBP",
    "ZAB"
]

COMPANY_KEYWORDS = {
    "INSIDER_TRADING": ["transakcj", "insider", "powiadomienie", "obowiązki zarządcze",
                        "obowiazki zarzadcze", "osoba", "19 mar", "19-mar", "mar 19", "mar-19",
                        "nabycie", "zbycie", "rozporządzenie", "rozporzadzenie"
                        ],
    "11BIT": ["11 bit", "11bit", "11-bit"],
    "ACAUTOGAZ": ["autogaz"],
    "AILLERON": ["ailleron"],
    "ALLEGRO": ["allegro"],
    "AMICA": ["amica"],
    "AMREST": ["amrest"],
    "APATOR": ["apator"],
    "ARCTIC": ["arctic"],
    "ARLEN": ["arlen"],
    "ASSECOSEE/ASSECOPL": ["asseco"],
    "AUTOPARTN": ["auto partner", "auto-partner", "autopartner"],
    "BIOCELTIX": ["bioceltix"],
    "BOGDANKA": ["bogdanka"],
    "BORYSZEW": ["boryszew"],
    "BOS": ["bank ochrony środowiska", "bankbos", "bankboś", "bank bos", "bank boś", "bank-bos", "bank-boś",
            "bank-ochrony-srodowiska"],
    "BUDIMEX": ["budimex"],
    "BUMECH": ["bumech"],
    "MDV": ["modivo", "ccc"],
    "CDPROJEKT": ["cd projekt", "cdprojekt", "cd-projekt"],
    "CELON": ["celon"],
    "CIGAMES": ["ci games"],
    "COGNOR": ["cognor"],
    "CREOTECH": ["creotech"],
    "CYFROWYPOLSAT": ["polsat", "cyfrowy"],
    "DATAWALK": ["datawalk"],
    "DIAG": ["diag"],
    "DINOPL": ["dino"],
    "ELEKTROTI": ["elektroti"],
    "ENTER": ["enter"],
    "ERBUD": ["erbud"],
    "EUROCASH": ["eurocash"],
    "FERRO": ["ferro"],
    "FORTE": ["forte"],
    "GRENEVIA": ["grenevia"],
    "GRUPAAZOTY": ["azoty"],
    "GRUPRACUJ": ["pracuj"],
    "HUUUGE": ["huuuge"],
    "KGHM": ["kghm"],
    "LUBAWA": ["lubawa"],
    "MABION": ["mabion"],
    "MCR": ["mcr"],
    "MEDICALG": ["medicalg"],
    "MENNICA": ["mennica"],
    "MERCATOR": ["mercator"],
    "MLSYSTEM": ["ml system", "mlsystem", "ml-system"],
    "MURAPOL": ["murapol"],
    "ONDE": ["onde"],
    "PCCROKITA": ["rokita"],
    "PEKABEX": ["pekabex"],
    "PEPCO": ["pepco"],
    "PGE": ["pge"],
    "PKNORLEN": ["orlen", "pkn"],
    "PLAYWAY": ["playway"],
    "POLENERGIA": ["polenergia"],
    "POLIMEXMS": ["polimex"],
    "QUERCUS": ["quercus"],
    "RYVU": ["ryvu"],
    "SELVITA": ["selvita"],
    "SHOPER": ["shoper"],
    "SNTVERSE": ["synthaverse", "sntverse"],
    "STALEXP": ["stalexp", "autostrad"],
    "TARCZYNSKI": ["tarczyński", "tarczynski"],
    "TEXT": ["text"],
    "TORPOL": ["torpol"],
    "TSGAMES": ["ten square", "tensquare", "ten-square", "ts games", "tsgames", "ts-games"],
    "UNIMOT": ["unimot"],
    "VOTUM": ["votum"],
    "VOXEL": ["voxel"],
    "WIELTON": ["wielton"],
    "WIRTUALNA": ["wirtualna"],
    "WITTCHEN": ["wittchen"],
    "XTB": ["xtb"],
    "ZEPAK": ["ze pak", "zepak", "ze-pak"]
}

WIG_SECTOR_BY_TICKER = {
    # banki
    "BOS": "WIG-BANKI",

    # budownictwo
    "BDX": "WIG-BUDOW",
    "ELT": "WIG-BUDOW",
    "PXM": "WIG-BUDOW",
    "TOR": "WIG-BUDOW",
    "PBX": "WIG-BUDOW",
    "ERB": "WIG-BUDOW",
    "OND": "WIG-BUDOW",
    "FRO": "WIG-BUDOW",
    "MCR": "WIG-BUDOW",

    # odzież / tekstylia
    "MDV": "WIG-ODZIEZ",
    "LBW": "WIG-ODZIEZ",
    "PCO": "WIG-ODZIEZ",
    "ARL": "WIG-ODZIEZ",
    "WTN": "WIG-ODZIEZ",

    # górnictwo
    "KGH": "WIG-GORNIC",
    "LWB": "WIG-GORNIC",
    "BMC": "WIG-GORNIC",

    # gry
    "CDR": "WIG-GRY",
    "11B": "WIG-GRY",
    "TEN": "WIG-GRY",
    "HUG": "WIG-GRY",
    "CIG": "WIG-GRY",
    "PLW": "WIG-GRY",

    # paliwa / energia
    "PKN": "WIG-PALIWA",
    "UNT": "WIG-PALIWA",
    "PGE": "WIG-ENERG",
    "MLS": "WIG-ENERG",
    "ZEP": "WIG-ENERG",
    "PEP": "WIG-ENERG",

    # spożywka / handel FMCG / restauracje
    "DNP": "WIG-SPOZYW",
    "EUR": "WIG-SPOZYW",
    "EAT": "WIG-SPOZYW",
    "TAR": "WIG-SPOZYW",

    # chemia
    "ATT": "WIG-CHEMIA",
    "PCR": "WIG-CHEMIA",

    # media
    "WPL": "WIG-MEDIA",
    "CPS": "WIG-MEDIA",

    # leki
    "MAB": "WIG-LEKI",
    "RVU": "WIG-LEKI",
    "SLV": "WIG-LEKI",
    "SVE": "WIG-LEKI",

    # informatyka
    "ALL": "WIG-INFO",
    "DAT": "WIG-INFO",
    "GPP": "WIG-INFO",
    "SNT": "WIG-INFO",
    "SHO": "WIG-INFO",
    "ACP": "WIG-INFO",
    "ASE": "WIG-INFO",

    # nieruchomości
    "MUR": "WIG-NRCHOM",

    # motoryzacja
    "BRS": "WIG-MOTO",
    "APR": "WIG-MOTO",
    "ACG": "WIG-MOTO",
    "WLT": "WIG-MOTO"
}

ALL = SWIG_80 + MWIG_40 + WIG_20
