
name: Run Python daily at 08:30 Europe/Warsaw

on:
  schedule:
    # Lato (kwiecień–październik): 06:30 UTC = 08:30 PL
    - cron: "2 6 * 4-10 *"
    # Zima (listopad–grudzień): 07:30 UTC = 08:30 PL
    - cron: "2 7 * 11-12 *"
    # Zima (styczeń–marzec): 07:30 UTC = 08:30 PL
    - cron: "2 7 * 1-3 *"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
        if: hashFiles('requirements.txt') != ''
      - name: Run script
        env:
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python rss.py
