
name: Run Python daily at 08:30 Europe/Warsaw

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
        if: hashFiles('requirements.txt') != ''
      - name: Run script
        env:
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python rss.py
